#!/bin/bash

export BASEROW_IMAGE_VERSION=1.33.4
export CLT_REQUIREMENTS_VERSION=2.2
export CLT_VERSION=14.2.1
export BASE_BASEROW_CLT_IMAGE_VARIANT=b
export COMBINED_BASE_VERSION=${BASEROW_IMAGE_VERSION}-${CLT_VERSION}-${BASE_BASEROW_CLT_IMAGE_VARIANT}
export BASE_BASEROW_CLT_IMAGE=vocabai/baserow-clt:${COMBINED_BASE_VERSION}